function [vertexVector] = threePartionPossibility (C_vertexDictionary, N_vertexDictionary, P_vertexDictionary, pattern, vertexVector)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 5 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
          
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
              
     elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    end
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 5 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 5 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
    if ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
        (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 4 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 4 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
     if ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
        (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 3 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 3 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
    
     if ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
        (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
     end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
    if ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
         (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
         (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
     end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 1 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 1 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
        (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
        (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(6).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(5).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
     elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(4).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(3).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(2).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
                
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
             (sum(sum(P_vertexDictionary.template - pattern(6).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(5).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(4).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(3).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(2).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    elseif ((sum(sum(C_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(N_vertexDictionary.template - pattern(1).template)))==0 && ...
            (sum(sum(P_vertexDictionary.template - pattern(1).template)))==0)
                vertexVector = cat(2,vertexVector, [3 1 ]);
    end

end
